#version 460

layout(set = 0, binding = 0, rgba8ui) uniform readonly uimage2D inputImg;

layout(set = 1, binding = 0, rgba8ui) uniform writeonly uimage2D outputImg;

layout(local_size_x = 32, local_size_y = 32, local_size_z = 1) in;

void main()
{
    ivec2 size = imageSize(inputImg);
    ivec2 coords = ivec2(gl_GlobalInvocationID.xy);
    imageStore(outputImg, coords, imageLoad(inputImg, size - coords));
}
